baseURL = "https://mukesh-tec.github.io/"
DefaultContentLanguage = "en"
title = "Mukesh Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Mukesh Chauhan"
author = "Mukesh Chauhan"
description = "Call me Mukesh"
profilePicture = "images/profile.jpg"
keywords = ["devops","aws","azure"]
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://in.linkedin.com/in/mukesh-chauhan-941400113"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/mukesh-tec"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/mukesh.chauhan.9003"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:canmu991@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"